function [kymograph, sz] = radial_kymograph_angularRange(stk, traj, theta_min, theta_max, dr, r_max)

% Number of time points
N_timePoints = length(stk);

% Initialize kymograph
ter1 = radial_histogram_angularRange(stk{1}, traj, theta_min, theta_max, dr, r_max);
sz = ter1(:, 4);
kymograph = zeros(N_timePoints, size(ter1, 1));
kymograph(1, :) = ter1(:, 2)';

% Each row of kymograph generated by radial histogram at that time point
for t=2:N_timePoints
    ter = radial_histogram_angularRange(stk{t}, traj, theta_min, theta_max, dr, r_max);
    kymograph(t, :) = ter(:, 2)';
end

sz = sz';

end